framework: jest
blocklist:
  - "jest-tests/alibaba.spec.js##Alibaba Search"
preRun:
     command:
        - node --version 
postMerge:
  pattern:
    - "./jest-tests/*.js"
preMerge:
  pattern:
    - "./jest-tests/*.js"
postRun:
     command:
        - node --version
version: 1.0 

